import { Question } from './types';

export const QUESTION_BANK: Question[] = [
  {
    id: 'is-1',
    category: 'Islamic Studies',
    question: 'اسلام کا پہلا رکن کیا ہے؟',
    options: ['نماز', 'کلمہ شہادت', 'زکوٰۃ', 'روزہ'],
    correctAnswer: 1,
  },
  {
    id: 'is-2',
    category: 'Islamic Studies',
    question: 'قرآن مجید میں کل کتنی سورتیں ہیں؟',
    options: ['110', '124', '114', '118'],
    correctAnswer: 2,
  },
  {
    id: 'is-3',
    category: 'Islamic Studies',
    question: 'کس نبی نے اپنے بیٹے اسماعیل کے ساتھ مل کر کعبہ تعمیر کیا؟',
    options: ['حضرت موسیٰؑ', 'حضرت آدمؑ', 'حضرت ابراہیمؑ', 'حضرت عیسیٰؑ'],
    correctAnswer: 2,
  },
  {
    id: 'is-4',
    category: 'Islamic Studies',
    question: 'مکہ کی زیارت کو عربی میں کیا کہتے ہیں؟',
    options: ['عمرہ', 'حج', 'زیارت', 'احرام'],
    correctAnswer: 1,
  },
  {
    id: 'is-5',
    category: 'Islamic Studies',
    question: 'کس مہینے میں روزہ فرض ہے؟',
    options: ['شوال', 'رجب', 'رمضان', 'محرم'],
    correctAnswer: 2,
  },
  {
    id: 'is-6',
    category: 'Islamic Studies',
    question: 'اسلام کے پہلے خلیفہ کون تھے؟',
    options: ['عمر بن الخطابؓ', 'علی بن ابی طالبؓ', 'عثمان بن عفانؓ', 'ابوبکر صدیقؓ'],
    correctAnswer: 3,
  },
  {
    id: 'is-7',
    category: 'Islamic Studies',
    question: 'نبی کریم ﷺ کے پاس پہلی وحی کون سا فرشتہ لایا؟',
    options: ['میکائیلؑ', 'جبرائیلؑ', 'اسرافیلؑ', 'عزرائیلؑ'],
    correctAnswer: 1,
  },
  {
    id: 'is-8',
    category: 'Islamic Studies',
    question: 'مسلمان دن میں کتنی بار نماز پڑھتے ہیں؟',
    options: ['3', '4', '5', '6'],
    correctAnswer: 2,
  },
  {
    id: 'is-9',
    category: 'Islamic Studies',
    question: 'قبلہ کا رخ کس طرف ہے؟',
    options: ['مدینہ', 'بیت المقدس', 'کعبہ', 'بغداد'],
    correctAnswer: 2,
  },
  {
    id: 'is-10',
    category: 'Islamic Studies',
    question: 'نبی کریم ﷺ کس شہر میں پیدا ہوئے؟',
    options: ['مکہ', 'مدینہ', 'طائف', 'جدہ'],
    correctAnswer: 0,
  },
  // Pakistan Studies
  {
    id: 'ps-1',
    category: 'Pakistan Studies',
    question: 'Who was the first Governor-General of Pakistan?',
    options: ['Liaquat Ali Khan', 'Quaid-e-Azam Muhammad Ali Jinnah', 'Khawaja Nazimuddin', 'Ghulam Muhammad'],
    correctAnswer: 1,
  },
  {
    id: 'ps-2',
    category: 'Pakistan Studies',
    question: 'When did Pakistan become a nuclear power?',
    options: ['1990', '1995', '1998', '2000'],
    correctAnswer: 2,
  },
  {
    id: 'ps-3',
    category: 'Pakistan Studies',
    question: 'What is the national flower of Pakistan?',
    options: ['Rose', 'Jasmine', 'Tulip', 'Sunflower'],
    correctAnswer: 1,
  },
  {
    id: 'ps-4',
    category: 'Pakistan Studies',
    question: 'Which is the highest peak in Pakistan?',
    options: ['Nanga Parbat', 'K2', 'Rakaposhi', 'Broad Peak'],
    correctAnswer: 1,
  },
  {
    id: 'ps-5',
    category: 'Pakistan Studies',
    question: 'Who wrote the national anthem of Pakistan?',
    options: ['Allama Iqbal', 'Hafeez Jalandhari', 'Faiz Ahmed Faiz', 'Josh Malihabadi'],
    correctAnswer: 1,
  },
  {
    id: 'ps-6',
    category: 'Pakistan Studies',
    question: 'In which year objective resolution was passed?',
    options: ['1947', '1948', '1949', '1950'],
    correctAnswer: 2,
  },
  {
    id: 'ps-7',
    category: 'Pakistan Studies',
    question: 'Which is the largest city of Pakistan?',
    options: ['Lahore', 'Islamabad', 'Karachi', 'Faisalabad'],
    correctAnswer: 2,
  },
  {
    id: 'ps-8',
    category: 'Pakistan Studies',
    question: 'What is the national language of Pakistan?',
    options: ['Punjabi', 'Sindhi', 'Urdu', 'Pashto'],
    correctAnswer: 2,
  },
  {
    id: 'ps-9',
    category: 'Pakistan Studies',
    question: 'When did East Pakistan separate from West Pakistan?',
    options: ['1965', '1969', '1971', '1973'],
    correctAnswer: 2,
  },
  {
    id: 'ps-10',
    category: 'Pakistan Studies',
    question: 'Who is known as "Poet of the East"?',
    options: ['Sir Syed Ahmed Khan', 'Allama Iqbal', 'Mirza Ghalib', 'Habib Jalib'],
    correctAnswer: 1,
  },
  // Adding more to reach closer to the requested volume behavior
  {
    id: 'ps-11',
    category: 'Pakistan Studies',
    question: 'What is the meaning of Pakistan?',
    options: ['Land of Rivers', 'Land of Mountains', 'Holy Land', 'Brave Land'],
    correctAnswer: 2,
  },
  {
    id: 'cs-1',
    category: 'Computer Science',
    question: 'What does HTML stand for?',
    options: ['HyperText Markup Language', 'HighText Machine Language', 'HyperLink Markup Linker', 'HyperTech Modern Language'],
    correctAnswer: 0,
  },
  {
    id: 'cs-2',
    category: 'Computer Science',
    question: 'What is considered the "brain" of the computer?',
    options: ['RAM', 'GPU', 'Hard Drive', 'CPU'],
    correctAnswer: 3,
  },
  {
    id: 'cs-3',
    category: 'Computer Science',
    question: 'Which language is primarily used for styling web pages?',
    options: ['HTML', 'JavaScript', 'CSS', 'Python'],
    correctAnswer: 2,
  },
  {
    id: 'cs-4',
    category: 'Computer Science',
    question: 'What is the most popular version control system?',
    options: ['Subversion', 'Git', 'Mercurial', 'Bazaar'],
    correctAnswer: 1,
  },
  {
    id: 'cs-5',
    category: 'Computer Science',
    question: 'What does RAM stand for?',
    options: ['Read Access Memory', 'Random Access Memory', 'Rapid Action Module', 'Real-time Async Memory'],
    correctAnswer: 1,
  },
  {
    id: 'cs-6',
    category: 'Computer Science',
    question: 'Which company originally developed Java?',
    options: ['Microsoft', 'Apple', 'Sun Microsystems', 'Google'],
    correctAnswer: 2,
  },
  {
    id: 'cs-7',
    category: 'Computer Science',
    question: 'What is the binary representation of decimal 5?',
    options: ['100', '101', '110', '111'],
    correctAnswer: 1,
  },
  {
    id: 'cs-8',
    category: 'Computer Science',
    question: 'What is a common way to store multiple values in a single variable?',
    options: ['Integer', 'Boolean', 'String', 'Array'],
    correctAnswer: 3,
  },
  {
    id: 'cs-9',
    category: 'Computer Science',
    question: 'What does URL stand for?',
    options: ['Universal Resource Link', 'Uniform Resource Locator', 'Unique Redirect Link', 'Unified Register List'],
    correctAnswer: 1,
  },
  {
    id: 'cs-10',
    category: 'Computer Science',
    question: 'In programming, what is a fixed value called?',
    options: ['Variable', 'Function', 'Constant', 'Loop'],
    correctAnswer: 2,
  },
  {
    id: 'sm-1',
    category: 'Social Media',
    question: 'Which social media platform is primarily focused on professional networking?',
    options: ['Instagram', 'Snapchat', 'LinkedIn', 'TikTok'],
    correctAnswer: 2,
  },
  {
    id: 'sm-2',
    category: 'Social Media',
    question: 'What is the character limit for a standard Tweet (post) on X (formerly Twitter)?',
    options: ['140', '280', '500', '1000'],
    correctAnswer: 1,
  },
  {
    id: 'sm-3',
    category: 'Social Media',
    question: 'Which company owns Instagram and WhatsApp?',
    options: ['Google', 'Microsoft', 'Meta', 'Apple'],
    correctAnswer: 2,
  },
  {
    id: 'sm-4',
    category: 'Social Media',
    question: 'What is the main format of content on TikTok?',
    options: ['Long-form articles', 'Static images', 'Short-form videos', 'Audio podcasts'],
    correctAnswer: 2,
  },
  {
    id: 'sm-5',
    category: 'Social Media',
    question: 'What does the term "Viral" mean in social media?',
    options: ['A computer virus', 'Content that spreads rapidly', 'Low engagement', 'Deleted content'],
    correctAnswer: 1,
  },
  {
    id: 'sm-6',
    category: 'Social Media',
    question: 'Which platform uses "Boards" and "Pins"?',
    options: ['Facebook', 'Pinterest', 'Reddit', 'Tumblr'],
    correctAnswer: 1,
  },
  {
    id: 'sm-7',
    category: 'Social Media',
    question: 'What is the primary purpose of a Hashtag (#)?',
    options: ['To tag friends', 'To format text', 'To categorize content', 'To private a post'],
    correctAnswer: 2,
  },
  {
    id: 'sm-8',
    category: 'Social Media',
    question: 'Which of these is a popular video-sharing platform owned by Google?',
    options: ['Vimeo', 'Dailymotion', 'YouTube', 'Twitch'],
    correctAnswer: 2,
  },
  {
    id: 'sm-9',
    category: 'Social Media',
    question: 'What is "SEO" in the context of digital presence?',
    options: ['Social Engine Optimization', 'Search Engine Optimization', 'Single Entry Option', 'Secure Electronic Order'],
    correctAnswer: 1,
  },
  {
    id: 'sm-10',
    category: 'Social Media',
    question: 'What is an "Influencer" in social media?',
    options: ['A platform developer', 'A user with a large following who can affect others', 'A customer support bot', 'A type of social media ad'],
    correctAnswer: 1,
  },
  {
    id: 'en-1',
    category: 'English',
    question: 'Which of these is a synonym for "Magnificent"?',
    options: ['Small', 'Splendid', 'Terrible', 'Boring'],
    correctAnswer: 1,
  },
  {
    id: 'en-2',
    category: 'English',
    question: 'Which sentence is grammatically correct?',
    options: ['They is going to the park.', 'Them are going to the park.', 'They are going to the park.', 'They am going to the park.'],
    correctAnswer: 2,
  },
  {
    id: 'en-3',
    category: 'English',
    question: 'What is the past tense of the verb "Run"?',
    options: ['Runs', 'Running', 'Ran', 'Runned'],
    correctAnswer: 2,
  },
  {
    id: 'en-4',
    category: 'English',
    question: 'Identify the noun in the sentence: "The blue sky is beautiful."',
    options: ['Blue', 'Sky', 'Beautiful', 'Is'],
    correctAnswer: 1,
  },
  {
    id: 'en-5',
    category: 'English',
    question: 'Which of these is an antonym for "Wealthy"?',
    options: ['Rich', 'Affluent', 'Poor', 'Prosperous'],
    correctAnswer: 2,
  },
  {
    id: 'en-6',
    category: 'English',
    question: 'What is a word that describes a verb?',
    options: ['Noun', 'Adjective', 'Adverb', 'Pronoun'],
    correctAnswer: 2,
  },
  {
    id: 'en-7',
    category: 'English',
    question: 'Choose the correct spelling:',
    options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'],
    correctAnswer: 2,
  },
  {
    id: 'en-8',
    category: 'English',
    question: 'Which of these is a conjunction?',
    options: ['Quickly', 'Because', 'Jump', 'Under'],
    correctAnswer: 1,
  },
  {
    id: 'en-9',
    category: 'English',
    question: 'A person who writes books is an...',
    options: ['Actor', 'Artist', 'Author', 'Architect'],
    correctAnswer: 2,
  },
  {
    id: 'en-10',
    category: 'English',
    question: 'What is the plural of "Child"?',
    options: ['Childs', 'Children', 'Childrens', 'Childes'],
    correctAnswer: 1,
  },
  {
    id: 'ma-1',
    category: 'Math',
    question: 'What is 15% of 200?',
    options: ['20', '30', '40', '50'],
    correctAnswer: 1,
  },
  {
    id: 'ma-2',
    category: 'Math',
    question: 'Solve for x: 2x + 5 = 15',
    options: ['5', '10', '15', '20'],
    correctAnswer: 0,
  },
  {
    id: 'ma-3',
    category: 'Math',
    question: 'What is the square root of 144?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
  },
  {
    id: 'ma-4',
    category: 'Math',
    question: 'How many sides does a hexagon have?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 1,
  },
  {
    id: 'ma-5',
    category: 'Math',
    question: 'What is 7 multiplied by 8?',
    options: ['54', '56', '58', '60'],
    correctAnswer: 1,
  },
  {
    id: 'ma-6',
    category: 'Math',
    question: 'If a triangle has angles 60° and 90°, what is the third angle?',
    options: ['30°', '45°', '60°', '90°'],
    correctAnswer: 0,
  },
  {
    id: 'ma-7',
    category: 'Math',
    question: 'What is 120 divided by 4?',
    options: ['25', '30', '35', '40'],
    correctAnswer: 1,
  },
  {
    id: 'ma-8',
    category: 'Math',
    question: 'Which of these is a prime number?',
    options: ['4', '9', '11', '15'],
    correctAnswer: 2,
  },
  {
    id: 'ma-9',
    category: 'Math',
    question: 'What is the value of Pi (to 2 decimal places)?',
    options: ['3.12', '3.14', '3.16', '3.18'],
    correctAnswer: 1,
  },
  {
    id: 'ma-10',
    category: 'Math',
    question: 'What is the perimeter of a square with side 5cm?',
    options: ['20cm', '25cm', '15cm', '10cm'],
    correctAnswer: 0,
  },
];
